package org.kysecurity.mail.pgp

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec

private const val ANDROID_KEYSTORE = "AndroidKeyStore"
private const val KEY_IV = "envelope_iv"
private const val KEY_CT = "envelope_ct"

/**
 * The durable half: an AES-256-GCM Keystore key that requires the device lock screen, and the
 * envelope re-sealed under it.
 *
 * The allowed authenticators include `DEVICE_CREDENTIAL` on purpose, so the key **survives a
 * biometric enrollment change**. Biometric-only would invalidate it whenever a fingerprint is
 * added, costing every ordinary user a full re-enrollment ceremony; and enrolling a biometric
 * already requires the device credential, so the attacker it would exclude already holds what this
 * key accepts. It also keeps `encryptionEnrolled` from flapping false for benign reasons — a marker
 * that cries wolf is one users learn to dismiss.
 *
 * The strict posture is not a switch here. It is Hostile Location Protection, under which there is
 * no envelope at all.
 */
internal class EnrollmentVault(context: Context) {

    private val appContext = context.applicationContext
    private val prefs: SharedPreferences by lazy { buildPrefs() }

    /**
     * False when the device has no secure lock screen. That is the honest outcome: the envelope's
     * protection *is* the lock screen, so a device without one cannot hold a meaningful one.
     *
     * An existing key is adopted only if it still carries the properties this design rests on.
     * Presence used to be the only test, which meant a key generated by an earlier build — with
     * different, possibly weaker parameters — was reused forever with no signal. Cross-app alias
     * squatting is impossible (Keystore is per-UID), so that was never remotely exploitable; the
     * reason it matters is that the design plans exactly the migration this silently breaks. The
     * authenticator set is fixed at generation, and the spec records changing it as "a one-line
     * change plus a re-enrollment prompt" — it would not have been, because the one-line change
     * would have been a no-op on every existing install.
     */
    fun ensureKey(): Boolean {
        if (existingKeyMatchesSpec()) return true
        return generate(strongBox = true) || generate(strongBox = false)
    }

    /** True only when a key exists AND still requires user authentication at the expected strength.
     *  Anything else is regenerated rather than trusted. */
    private fun existingKeyMatchesSpec(): Boolean = runCatching {
        val ks = keyStore()
        if (!ks.containsAlias(ALIAS)) return false
        val key = ks.getKey(ALIAS, null) as? SecretKey ?: return false
        val info = SecretKeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE)
            .getKeySpec(key, KeyInfo::class.java) as KeyInfo
        info.isUserAuthenticationRequired && info.keySize == 256
    }.getOrElse {
        // An unreadable key is not a usable key. Regenerating is the safe direction: it costs a
        // re-enrollment, where adopting an unverifiable key costs the property the vault exists for.
        Log.i("EnrollmentVault", "Existing vault key could not be inspected; regenerating", it)
        false
    }

    /**
     * Generates the vault key, and **clears any stored blob in the same breath**.
     *
     * A newly minted key can never open an envelope sealed under a previous one, so retaining the
     * blob across a regeneration is never correct — and it is actively harmful, because
     * [probeEnrollment] establishes only that *a* key exists and that *a* blob exists. `Cipher.init`
     * on GCM touches no ciphertext, so it succeeds against the wrong key, and the probe then reports
     * ENROLLED for a blob nothing in the world can decrypt. The server renders that to the user as
     * "this device can read your encrypted mail", which is the exact lie the marker exists to
     * prevent, and it is the unsafe direction: a user may decommission the device that actually
     * holds a working copy.
     *
     * Reachable whenever the OS destroys the key without any of our code running — the user removing
     * and re-adding the device lock screen is enough.
     */
    private fun generate(strongBox: Boolean): Boolean = runCatching {
        val spec = KeyGenParameterSpec.Builder(
            ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setRandomizedEncryptionRequired(true)
            .setUserAuthenticationRequired(true)
            // 0 = per-use auth, satisfied through a BiometricPrompt.CryptoObject.
            .setUserAuthenticationParameters(
                0,
                KeyProperties.AUTH_BIOMETRIC_STRONG or KeyProperties.AUTH_DEVICE_CREDENTIAL,
            )
            .apply { if (strongBox) setIsStrongBoxBacked(true) }
            .build()
        // Before anything else: a blob sealed under a previous key is unopenable by the key we are
        // about to mint, and keeping it makes probeEnrollment report ENROLLED for a device that can
        // decrypt nothing. Clear it first so an interruption between here and generateKey leaves
        // "no key, no blob" rather than "new key, stale blob".
        prefs.edit().clear().commit()
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            .apply { init(spec) }
            .generateKey()
        true
    }.getOrElse {
        if (strongBox) Log.i("EnrollmentVault", "StrongBox unavailable, falling back to TEE")
        else Log.e("EnrollmentVault", "Could not generate the vault key", it)
        false
    }

    fun sealCipher(): Cipher? = runCatching {
        Cipher.getInstance("AES/GCM/NoPadding").apply { init(Cipher.ENCRYPT_MODE, secretKey()) }
    }.getOrNull()

    fun openCipher(iv: ByteArray): Cipher? = runCatching {
        Cipher.getInstance("AES/GCM/NoPadding")
            .apply { init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(128, iv)) }
    }.getOrNull()

    fun store(iv: ByteArray, ciphertext: ByteArray) {
        prefs.edit()
            .putString(KEY_IV, Base64.encodeToString(iv, Base64.NO_WRAP))
            .putString(KEY_CT, Base64.encodeToString(ciphertext, Base64.NO_WRAP))
            .commit()
    }

    /** A corrupt or undecodable blob reads as "no blob", never as an exception: the callers of this
     *  are a background worker and the app-foreground path, and a throw there freezes the enrollment
     *  marker at its last value rather than correcting it. */
    fun stored(): Pair<ByteArray, ByteArray>? = runCatching {
        val iv = prefs.getString(KEY_IV, null) ?: return null
        val ct = prefs.getString(KEY_CT, null) ?: return null
        Base64.decode(iv, Base64.NO_WRAP) to Base64.decode(ct, Base64.NO_WRAP)
    }.getOrNull()

    fun hasBlob(): Boolean = runCatching { prefs.contains(KEY_CT) }.getOrDefault(false)

    /**
     * Destroys the sealed blob and the vault key, and **reports what it could not destroy**.
     *
     * Its own prefs file, not `SecurePairingStore`'s, so this is a file delete plus one alias
     * removal — with no risk of clearing pairing state that Hostile Location Protection explicitly
     * preserves.
     *
     * Returns the names of the steps that failed; empty means everything is gone. It used to return
     * `Unit` with three bare `runCatching {}` blocks and the `deleteSharedPreferences` boolean
     * discarded — so it could not fail however badly it went. That matters because the design has it
     * called as a `SecurityWipe.step(...)`, and `step` records a failure only if the body throws:
     * a half-failed teardown would have been reported as a complete one, and Hostile Location
     * Protection would flip on announcing success with the sealed private key still on disk.
     * `SecurityWipe`'s own KDoc already names this exact anti-pattern as a defect it fixed elsewhere.
     */
    fun destroy(): List<String> {
        val failed = mutableListOf<String>()
        runCatching { prefs.edit().clear().commit() }
            .onFailure { failed += "clearBlob"; Log.e("EnrollmentVault", "Could not clear the blob", it) }
        // deleteSharedPreferences returns false when the file is still there — the one signal that
        // the sealed envelope survived. Discarding it was how this reported success over a live blob.
        val fileGone = runCatching { appContext.deleteSharedPreferences(PREFS_FILE) }.getOrDefault(false)
        if (!fileGone && runCatching { hasBlob() }.getOrDefault(true)) failed += "deletePrefsFile"
        runCatching {
            val ks = keyStore()
            ks.deleteEntry(ALIAS)
            if (ks.containsAlias(ALIAS)) error("alias survived deleteEntry")
        }.onFailure { failed += "deleteKey"; Log.e("EnrollmentVault", "Could not delete the vault key", it) }
        return failed
    }

    internal fun secretKey(): SecretKey = keyStore().getKey(ALIAS, null) as SecretKey

    private fun keyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    /**
     * Builds the encrypted store, resetting it if the Tink keyset can no longer be decrypted.
     *
     * `androidx.security-crypto` is deprecated precisely because `EncryptedSharedPreferences.create`
     * throws on an unreadable keyset — an OS-level key invalidation, a restored backup. Both siblings
     * in this codebase already handle it this way and say why: `SecurePairingStore.buildEncryptedPrefs`
     * and `AppLockStore.buildEncryptedPrefs`, the latter noting "an uncaught failure here crashes the
     * app on every launch". This store had none of it, so the one event the enrollment marker is
     * probed rather than cached *for* — the key going away without our code running — made the probe
     * throw instead of reporting.
     *
     * Failing closed is right here: a lost blob reads as "not enrolled", which is the safe direction.
     */
    private fun buildPrefs(): SharedPreferences = try {
        createPrefs()
    } catch (e: Exception) {
        Log.e("EnrollmentVault", "Envelope store unreadable, resetting", e)
        appContext.deleteSharedPreferences(PREFS_FILE)
        createPrefs()
    }

    private fun createPrefs(): SharedPreferences {
        val masterKey = MasterKey.Builder(appContext).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build()
        return EncryptedSharedPreferences.create(
            appContext,
            PREFS_FILE,
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    companion object {
        const val ALIAS = "kypost_device_envelope_seal"
        const val PREFS_FILE = "device_envelope_secure"
    }
}
