package com.urlxl.mail.pgp

/**
 * A disposable, passphrase-free ed25519/cv25519 pair and one message encrypted and signed to it,
 * both produced by `gpg` — deliberately a different OpenPGP implementation from the Bouncy Castle
 * code under test, for the reason [TestPgpKey] gives: a fixture generated by the implementation
 * being tested only proves the code agrees with itself.
 *
 * Never a real key. Regenerate with the commands in this task's plan step if it needs replacing.
 */
internal object TestPgpPrivateKey {
    const val FINGERPRINT = "B30A CD64 E04B 8E1B 0379  A320 1D6B DF09 3FAD 1D11"

    /** Decrypts to exactly [EXPECTED_PLAINTEXT], signed by this same key. */
    const val EXPECTED_PLAINTEXT = "Hello from a real OpenPGP message.\n"

    val ARMORED_PRIVATE = """
        -----BEGIN PGP PRIVATE KEY BLOCK-----

        lFgEanXKfhYJKwYBBAHaRw8BAQdA2rBAx6x5YF+ObBFQBXF+/2csH6f0qPdhr1ag
        i2N5i44AAQCcI5HtSSpyFdm1apjsdPP/oSSL46Btyofhqqe7izRdLhHitCpQZ3BE
        ZWNyeXB0b3JUZXN0IDxkZWNyeXB0QGV4YW1wbGUuaW52YWxpZD6IkAQTFgoAOBYh
        BLMKzWTgS44bA3mjIB1r3wk/rR0RBQJqdcp+AhsDBQsJCAcCBhUKCQgLAgQWAgMB
        Ah4BAheAAAoJEB1r3wk/rR0RGwIA/3DvjicIsZAjVJYjTdPCsYrYbycQ6JUmtKEF
        zHjImBW4AQDinfWUlzlme+nnz+Ba//Axhd1mG5jbCzvbuBqdaFO0D5xdBGp1yoMS
        CisGAQQBl1UBBQEBB0B1Hj+iZWHELCD46VW53zsWvt/gaj5zmPw8Q3zTJRNydAMB
        CAcAAP9MfEiba0BwC3gPCGNnBSpVT6ItjQ2pBmc/6tkGpZmyOAyriHgEGBYKACAW
        IQSzCs1k4EuOGwN5oyAda98JP60dEQUCanXKgwIbDAAKCRAda98JP60dEYRUAP9v
        3DLng8XERhSTtj1xklvWLmm+PNj9sIfTevTwFlR1EwEAqFTrsMbz8SfXD5x0TvHL
        KrCer7RkZAcLVY8rcoru9Ao=
        =56KP
        -----END PGP PRIVATE KEY BLOCK-----
    """.trimIndent()

    val ARMORED_MESSAGE = """
        -----BEGIN PGP MESSAGE-----

        hF4DIE6jVovIid0SAQdAGRbD7Tnkx/XA3SYjkTeY5cHfPkY7TzOUolNd9Yw38Uow
        miO6k16SpQCyugWrXGUE9kpTuVLw6+i8hHTfwCl9asERt0cNvp3MLklxjmiTGgwO
        0sAaAYGxUQZ4CukpripClMv7C5F4u8MSa+PfHFYViEL/sie2alUtWEYijrcmpr8r
        DHjuFCddDnUBT70SA4DDt+VxwQdS7R5FgY9vUf/WgdcjnP6DZpua6LjegMyjgJg3
        1fd58ly3ZLkPGe3LzNzvJ9YouCZsvKaPYMeb3sw+VQL9ZQaNzD23zkSrvkwc2gQ1
        NCo8FMo5AKlEZKUkoL9euSY/d09tCpZlJk/hjEkizqw67Bjk/jzirNTWaZsGsf9y
        U5qTeneHshndLGw3O6ncuPQBWHANvJU07E/TmgQ=
        =/cZ5
        -----END PGP MESSAGE-----
    """.trimIndent()
}
